### PR TITLE
feat: generic resources tracking

### PR DESCRIPTION
**Pull request by ilya-lesikov**
Signed-off-by: Ilya Lesikov <ilya@lesikov.com>

### CODE REVIEW

**Comment by dudicoco** [comment]
@ilya-lesikov can you please elaborate on how this feature works?
Nothing was added to the docs.

**Comment by ilya-lesikov** [comment]
@dudicoco This feature adds new type of Spec (Generic Spec) which can be used for resources with any Kinds. It will try to determine the Ready/NotReady status of a resource by heuristically inspecting some of its status fields. It is also collects events of the resource. The purpose of this is to be used for all the resources that are not supported natively by more specific trackers (Deployment, Daemonset, Job, Statefulset, Canary).

Used the same way as regular trackers:
```
	err = multitrack.Multitrack(kube.Kubernetes, multitrack.MultitrackSpecs{
		Deployments: []multitrack.MultitrackSpec{
			{ResourceName: "tiller-deploy", Namespace: "kube-system"},
			{ResourceName: "coredns", Namespace: "kube-system"},
		},
		Jobs: []multitrack.MultitrackSpec{
                  ...
		},
		Generics: []*generic.Spec{
		   ...
                },
	}, multitrack.MultitrackOptions{})
```

**Comment by shurup** [comment]
Hi @dudicoco! Thank you for your reasonable question! We acknowledge it's not how it should be typically done, but surely we'll add documentation for this feature soon.

**Comment by dudicoco** [comment]
Thanks @ilya-lesikov and @shurup

**Pull request merged**
